### ISSUE TITLE
This is just a suggestion

### ISSUE THREAD

**Issue by Falling10fruit** [RebornTrack970/MindustryAU#2]
How about some lore? Like when the Crux landed and started to colonize the planet... Created those spores that eventually took over the planet... Ect. If you don't like the suggestion, just close the issue. Thanks for giving some effort to reading my suggestion.

**Comment by RebornTrack970** [comment]
neat idea but the v6 version doesnt have much lore, just waiting for v7 full release.

**Comment by Falling10fruit** [comment]
Oh okay, how about what happens after the planet gets colonized by the Sharded? Maybe about other sharded "players" (They are probably not going to be called players, right?) joining the planet that explains why multiplayer exists... Um... Now that I think of that... That shouldn't be explaining multiplayer since no game lore does that. It's a game thing and lore probably doesn't explain that... I don't know, this is just a suggestion so it's your choice I guess.

**Comment by Falling10fruit** [comment]
Lol, I was actually using this lore as a guide for Ruinous Shores.

**Comment by Falling10fruit** [comment]
Also, I don't think there are people and they're just AIs since I'm still alive after the unit I'm controlling died. As if I was in the Core controlling the unit using WiFi.

**Comment by Falling10fruit** [comment]
Whoops. Also, do you want to put this up on a website? I have a little bit of experience with CSS and HTML.

**Comment by Falling10fruit** [comment]
/“The Emperor will not be please.” Said the Commander, with a low and deep voice.
Also, I think it's supposed to be “The Emperor will not be please _*d*_.”

**Comment by RebornTrack970** [comment]
> /“The Emperor will not be please.” Said the Commander, with a low and deep voice.
> Also, I think it's supposed to be “The Emperor will not be please __d__.”

Thanks

**Comment by RebornTrack970** [comment]
> Whoops. Also, do you want to put this up on a website? I have a little bit of experience with CSS and HTML.

I mean, it is on Github, so i dont think i need to.

**Comment by RebornTrack970** [comment]
> Also, I don't think there are people and they're just AIs since I'm still alive after the unit I'm controlling died. As if I was in the Core controlling the unit using WiFi.

They are Droids. Thats why they have names like “Commander” “Admiral” “Captain” etc and not actual human names.
